name: "Rust CI"
on:
  pull_request:

jobs:
  build:
    name: cargo build and test
    strategy:
      matrix:
        # Needs big runners to run tests
        # Only macos-13-xlarge is Apple Silicon, as per:
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners#about-macos-larger-runners
        os: [ubuntu-22.04-github-hosted-16core, macos-13-xlarge]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo build --verbose
      - run: cargo test --verbose --all
       
  build_old:
    name: cargo build and test (packed_simd)
    strategy:
      matrix:
        # Needs big runners to run tests
        # Only macos-13-xlarge is Apple Silicon, as per:
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners#about-macos-larger-runners
        os: [ubuntu-22.04-github-hosted-16core, macos-13-xlarge]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly-2023-05-31 

      # Still compile the old rust nightly with packed simd - until we have a good replacement in poseidon.
      - run: RUSTFLAGS=-Awarnings cargo +nightly-2023-05-31 build --features include_packed_simd
      - run: RUSTFLAGS=-Awarnings cargo +nightly-2023-05-31 test --features include_packed_simd

  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
